;; ============================================================
;; ui_events.lisp - event handlers (generated by LVGL UI Editor)
;; ============================================================
;; Handlers are registered in ui.lisp with lv-obj-add-event-cb and called from the main loop.

(defun ui-event-main1-speed-prev-clicked (e)
  (progn
    ;; Navigate to: main2_diagnostics
    (ui-load-screen-main2-diagnostics)
    nil))

(defun ui-event-main1-speed-next-clicked (e)
  (progn
    ;; Navigate to: main1_charts
    (ui-load-screen-main1-charts)
    nil))

(defun ui-event-main1-charts-prev-clicked (e)
  (progn
    ;; Navigate to: main1_speed
    (ui-load-screen-main1-speed)
    nil))

(defun ui-event-main1-charts-next-clicked (e)
  (progn
    ;; Navigate to: main1_temperature
    (ui-load-screen-main1-temperature)
    nil))

(defun ui-event-main1-temperature-prev-clicked (e)
  (progn
    ;; Navigate to: main1_charts
    (ui-load-screen-main1-charts)
    nil))

(defun ui-event-main1-temperature-next-clicked (e)
  (progn
    ;; Navigate to: main2_settings
    (ui-load-screen-main2-settings)
    nil))

(defun ui-event-main2-settings-prev-clicked (e)
  (progn
    ;; Navigate to: main1_temperature
    (ui-load-screen-main1-temperature)
    nil))

(defun ui-event-main2-settings-next-clicked (e)
  (progn
    ;; Navigate to: main2_statistics
    (ui-load-screen-main2-statistics)
    nil))

(defun ui-event-main2-statistics-prev-clicked (e)
  (progn
    ;; Navigate to: main2_settings
    (ui-load-screen-main2-settings)
    nil))

(defun ui-event-main2-statistics-next-clicked (e)
  (progn
    ;; Navigate to: main2_diagnostics
    (ui-load-screen-main2-diagnostics)
    nil))

(defun ui-event-main2-diagnostics-prev-clicked (e)
  (progn
    ;; Navigate to: main2_statistics
    (ui-load-screen-main2-statistics)
    nil))

(defun ui-event-main2-diagnostics-next-clicked (e)
  (progn
    ;; Navigate to: main1_speed
    (ui-load-screen-main1-speed)
    nil))

;; USER CODE BEGIN events_custom
;; USER CODE END events_custom
