;; ============================================================
;; ui_logic.lisp - logic graphs (generated by LVGL UI Editor)
;; ============================================================
;; ui-logic-init registers the triggers, ui-logic-tick runs the timers (called from the main loop).

;; ============================================================
;; Logic variables
;; ============================================================
(def var-uptime 0)

;; ============================================================
;; Logic functions
;; ============================================================
;; Logic: Max speed caption
(defun logic-max-speed-caption ()
  (progn
    ;; Event: LV_EVENT_VALUE_CHANGED on slider-61
    (lv-label-set-text ui-max-speed-label (str-merge (str-from-n (lv-slider-get-value ui-max-speed-slider) "%d") " km/h"))
    nil))

;; Logic: Max speed bar follows the slider
(defun logic-max-speed-bar-follows-the-slider ()
  (progn
    (lv-bar-set-value ui-max-speed-bar (lv-slider-get-value ui-max-speed-slider) LV_ANIM_ON)
    nil))

;; Logic: Uptime counter
(defun logic-uptime-counter ()
  (progn
    ;; Timer: repeat, 1000ms
    (setq var-uptime (+ var-uptime 1))
    (lv-label-set-text ui-uptime-label (str-merge (str-from-n var-uptime "%d") " s"))
    nil))

;; Logic: SD card LED blinks
(defun logic-sd-card-led-blinks ()
  (progn
    ;; Timer: repeat, 500ms
    (if (lv-obj-has-flag ui-sd-led LV_OBJ_FLAG_HIDDEN)
        (lv-obj-remove-flag ui-sd-led LV_OBJ_FLAG_HIDDEN)
        (lv-obj-add-flag ui-sd-led LV_OBJ_FLAG_HIDDEN))
    nil))

(defun logic-max-speed-caption-on-event (e) (logic-max-speed-caption))

;; ============================================================
;; Init and timers
;; ============================================================
(defun ui-logic-init ()
  (progn
    (lv-obj-add-event-cb ui-max-speed-slider 'logic-max-speed-caption-on-event LV_EVENT_VALUE_CHANGED)
    (def logic-uptime-counter-timer0 (systime))
    (def logic-uptime-counter-timer0-done nil)
    (def logic-sd-card-led-blinks-timer0 (systime))
    (def logic-sd-card-led-blinks-timer0-done nil)
    nil))

;; ============================================================
;; Deferred calls (Delay nodes)
;; ============================================================
(def ui-defer-queue nil)
(def ui-live-t (systime))

(defun ui-defer (secs f)
  (setq ui-defer-queue (cons (list (systime) secs f) ui-defer-queue)))

(defun ui-defer-tick ()
  (if (eq ui-defer-queue nil)
    nil
    (let ((q ui-defer-queue))
      (progn
        (setq ui-defer-queue nil)
        (map (lambda (d)
            (if (>= (secs-since (ix d 0)) (ix d 1))
              (trap ((ix d 2)))
              (setq ui-defer-queue (cons d ui-defer-queue))))
          q)
        nil))))

;; ============================================================
;; Live graphs (no trigger)
;; ============================================================
(def logic-max-speed-bar-follows-the-slider-sig nil)
(defun logic-max-speed-bar-follows-the-slider-live ()
  (let ((s (list (lv-slider-get-value ui-max-speed-slider))))
    (if (eq s logic-max-speed-bar-follows-the-slider-sig)
      nil
      (progn (setq logic-max-speed-bar-follows-the-slider-sig s) (logic-max-speed-bar-follows-the-slider)))))

(defun ui-logic-tick ()
  (progn
    (ui-defer-tick)
    (if (>= (secs-since ui-live-t) 0.05)
        (progn (setq ui-live-t (systime)) (logic-max-speed-bar-follows-the-slider-live)))
    (if (>= (secs-since logic-uptime-counter-timer0) 1.0)
        (progn (setq logic-uptime-counter-timer0 (systime)) (logic-uptime-counter)))
    (if (>= (secs-since logic-sd-card-led-blinks-timer0) 0.5)
        (progn (setq logic-sd-card-led-blinks-timer0 (systime)) (logic-sd-card-led-blinks)))
    nil))

;; USER CODE BEGIN logic_custom
;; USER CODE END logic_custom
