;; ============================================================
;; main.lisp - entry point (generated by LVGL UI Editor)
;; ============================================================
;; Open this file in VESC Tool (Lisp tab) and press Upload: the (import ...) lines
;; below bundle the files of the ui/ folder, so keep ui/ next to main.lisp.

;; ============================================================
;; Code
;; ============================================================
(import "ui/ui.lisp" 'ui-code)
(import "ui/ui_events.lisp" 'ui-events-code)
(import "ui/ui_logic.lisp" 'ui-logic-code)

;; ============================================================
;; Load
;; ============================================================
(read-eval-program ui-code)
(read-eval-program ui-events-code)
(read-eval-program ui-logic-code)

;; ============================================================
;; Build the UI
;; ============================================================
(lv-batch 1)
(ui-init)
(ui-logic-init)
(lv-batch 0)

;; ============================================================
;; Event loop
;; ============================================================
;; The LVGL task queues events; handlers run here, in the Lisp thread.
(defun ui-poll ()
  (let ((e (lv-event-poll)))
    (if e
        (progn
          (trap (eval (list (lv-event-get-cb e) (list 'quote e))))
          t)
        nil)))

(defun ui-run ()
  (progn
    (if (not (ui-poll)) (lv-event-wait 0.02))
    (trap (ui-anim-step))
    (trap (ui-logic-tick))
    (ui-run)))

(ui-run)
