// main.lisp generator: entry point that loads the ui/ files and runs the event loop

import type { Page } from '../../types';
import type { ImageResource, FontResource } from '../../resources/types';
import type { LispGenOptions } from './types';
import { banner, comment } from './sexp';
import { collectUsedImages, collectUsedCustomFonts, imageDataSym, fontDataSym } from './ui';

export function generateMainLisp(
  pages: Page[],
  options: LispGenOptions,
  imageResources: ImageResource[],
  fontResources: FontResource[],
  defaultFont?: string,
  defaultFontSize?: number
): string {
  const L: string[] = [];
  L.push(...banner('main.lisp - entry point (generated by LVGL UI Editor)'));
  L.push(comment('Open this file in VESC Tool (Lisp tab) and press Upload: the (import ...) lines'));
  L.push(comment('below bundle the files of the ui/ folder, so keep ui/ next to main.lisp.'));
  L.push('');

  L.push(...banner('Code'));
  L.push('(import "ui/ui.lisp" \'ui-code)');
  L.push('(import "ui/ui_events.lisp" \'ui-events-code)');
  L.push('(import "ui/ui_logic.lisp" \'ui-logic-code)');
  L.push('');

  const images = collectUsedImages(pages, imageResources);
  const fonts = collectUsedCustomFonts(pages, fontResources, defaultFont, defaultFontSize);
  if (images.length > 0 || fonts.size > 0) {
    L.push(...banner('Resources (VESC .bin files)'));
    L.push(comment('Export these from VESC Tool and put them in the folders below, next to main.lisp.'));
    for (const img of images) {
      L.push(`(import "assets/${img.cArrayName}.bin" '${imageDataSym(img, options)})`);
    }
    for (const [name, sizes] of fonts) {
      for (const s of [...sizes].sort((a, b) => a - b)) {
        L.push(`(import "font/${name}_${s}.bin" '${fontDataSym(name, s, options)})`);
      }
    }
    L.push('');
  }

  L.push(...banner('Load'));
  L.push('(read-eval-program ui-code)');
  L.push('(read-eval-program ui-events-code)');
  L.push('(read-eval-program ui-logic-code)');
  L.push('');

  L.push(...banner('Build the UI'));
  L.push('(lv-batch 1)');
  L.push('(ui-init)');
  L.push('(ui-logic-init)');
  L.push('(lv-batch 0)');
  L.push('');

  L.push(...banner('Event loop'));
  L.push(comment('The LVGL task queues events; handlers run here, in the Lisp thread.'));
  L.push('(defun ui-poll ()');
  L.push('  (let ((e (lv-event-poll)))');
  L.push('    (if e');
  L.push('        (progn');
  L.push('          (trap (eval (list (lv-event-get-cb e) (list \'quote e))))');
  L.push('          t)');
  L.push('        nil)))');
  L.push('');
  L.push('(defun ui-run ()');
  L.push('  (progn');
  L.push('    (if (not (ui-poll)) (lv-event-wait 0.02))');
  L.push('    (trap (ui-anim-step))');
  L.push('    (trap (ui-logic-tick))');
  L.push('    (ui-run)))');
  L.push('');
  L.push('(ui-run)');
  L.push('');
  return L.join('\n');
}
